### ISSUE TITLE
Extended CSS

### ISSUE THREAD

**Issue by piquark6046** [craftingmod/quasarblock#1]
아직 Firefox가 `:has()`를 지원하지 않아, AdGuard와 uBlock Origin 같은 광고 차단기에서는 `:has()`의 사용을 Extended CSS로 간주하기에 `##` 대신에 `#?#`를 사용하시는 게 좋습니다.

**Comment by craftingmod** [comment]
https://adguard.com/kb/ko/general/ad-filtering/create-own-filters/ 에 참고하여
Extended CSS를 사용하도록 바꿨습니다.

이슈 제보 및 자세한 수정 방법 알려주셔서 감사합니다! :)

**Comment by piquark6046** [comment]
다른 이야기인데요. 퀘이사존에 가입한 적은 있었는데 규정 때문에 정지 먹을 것 같아서 그냥 자진 탈퇴했거든요.
그래서 그냥 [List-KR repo](https://github.com/List-KR/List-KR)의 GitHub Discussion으로 질문 받습니다.

**Comment by craftingmod** [comment]
사실 이 필터가 광고 차단을 위한 필터가 아니라 퀘이사존에 한정해서 차단을 해도 흔적이 남는 사이트 디자인 문제를 수정하기 위한 필터라 (+요즘 이슈되는 유머 게시판 베스트 관련 조치도 있습니다.) List-KR에 Discussion/PR 하기에는 광고 차단 역할을 수행할 수 없는 것도 있고 사용자의 호/불호 문제가 있어서 List-KR이 아닌 개인 레포에다가 저장해뒀습니다.

향후 광고 관련해서는 List-KR의 GitHub Discussion을 사용하도록 하겠습니다. 감사합니다!

**Comment by piquark6046** [comment]
퀘이사존의 그 글에서 유니콘에 추가하면 동작하냐는 말이 있어서 드리는 내용인데요.
유니콘 및 유니콘 Pro는 scriptlets와 Extended CSS 같은 고급 문법을 지원하지 않기에 추가해도 의미가 없습니다.
